@startuml microservices
skinparam backgroundcolor transparent

component "User App" as userapp
node Gateway
node Payment
node Auth
node Appointment
database Database


userapp -- Gateway

Gateway -- Payment
Gateway -- Auth
Gateway -- Appointment

Payment ..> Database
Auth ..> Database
Appointment ..> Database
Appointment ..> Database
Appointment ..> Database

@enduml